# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

on:
  pull_request:
    paths-ignore:
      - 'scripts/**'
      - 'middleware/**'
      
trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'SSH_serviceconnection'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '''**/*.apk'''
    targetFolder: '/var/www/adhoc/dev/'
    readyTimeout: '40000'

